### ISSUE TITLE
Struggling with setting up the bot.

### ISSUE THREAD

**Issue by LeighLeighh** [azh412/VirtualPianoBot#5]
When I type 'cd downloads' the prompt that appears is:
File "<stdin>", line 1
cd downloads
         ^
SyntaxError: invalid syntax

On Windows 11 and using Python 3.8.
(Note that I have no clue what any of this means lmao)

**Comment by azh412** [comment]
Hello!

If I recall correctly, the downloads folder in Windows can be accessed through `cd Downloads`. 
The point of the `cd` command is to change the terminal focus to that folder, so you can execute commands relevant to that folder's contents.
These commands should be executed in the `terminal`, not a Python file.
If you need anything else, create another issue, I'll close this one for now. Thanks!

-azh
